language: python

services:
    - docker

before_install:
    - docker build -t minimalctf:ubuntu19.10 ./minimalctf/
    - docker image ls
    - docker run --rm --volume $PWD:/pwd --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -d --name minimalctf -i minimalctf:ubuntu19.10
    - docker container ls

